apiVersion: apps/v1
kind: Deployment
metadata:
  name: seiodck
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seiodck
  template:
    metadata:
      labels:
        app: seiodck
    spec:
      containers:
      - image: okteto.dev/seiodck:latest
        name: seiodck
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "0e0a7b44-fc78-4c93-af92-0440fd967f9b"
        - name: Vless_Path
          value: "/0e0a7b44-fc78-4c93-af92-0440fd967f9b-vless"
        - name: Vmess_UUID
          value: "0e0a7b44-fc78-4c93-af92-0440fd967f9b"
        - name: Vmess_Path
          value: "/f619adae-79e2-4158-9f86-d06bd3c44a8a-vmess"
        - name: Share_Path
          value: "$Share_Path"
